# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
